upstream deeplx_backend {
    server   127.0.0.1:8449;
}

# https
server
{
    ssl_certificate     /etc/nginx/conf.d/deeplxweb.cer;
    ssl_certificate_key /etc/nginx/conf.d/deeplxweb.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    listen 9449 ssl http2;
    server_name  deeplxweb.yourdomain.com; # 替换为你的域名
    root /usr/share/nginx/html/deeplx-html;
    index index.html;

    # SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass        http://deeplx_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /health {
        proxy_pass http://deeplx_backend;
        proxy_http_version 1.1;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}